### ISSUE TITLE
Data Import Error

### ISSUE THREAD

**Issue by jsabhishek** [Nicktz/rmsfuns#4]
Hello Sir,
I am a student pursuing my second year of MBA in India. I came across a post of yours - 
Volatility Modelling on curiousquant.com
Link - http://curiousquant.com/ClassNotes/FinMetrics/Practicals/Practical_6/Practical_6.html#
There is an error while importing the csv file.
Code - read_csv("https://raw.githubusercontent.com/Nicktz/Nicktz.github.io/master/inst/extdata/findata.csv?token=AOMtNrLZwdGvYjsMuZXjFwuKs6Q0MIDDks5ZzQFcwA%3D%3D"
Error - 404: Not Found
 
Can you upload the csv file please, it will be helpful for my project. Waiting for your reply.
Many Thanks
J S Abhishek

**Comment by Nicktz** [comment]
Hi JS, see the updated version on the new website for the notes here:

https://finmx.nfkatzke.com/notes

You should now have no loading issues..

**Comment by jsabhishek** [comment]
Many Thanks for your timely help, Sir.
Sir, I do have some academic doubts. How can I ask you ? 
I've sent you a request on Linkedin. Is it ok, Sir.
Thanks a lot
J S Abhishek

**Comment by Nicktz** [comment]
Hi JS,

Please rather mail me if you have any queries.

You can find my email address on the website.

N
